### ISSUE TITLE
use of SPDX identifiers

### ISSUE THREAD

**Issue by jlovejoy** [jywarren/certification-mark-generator#2]
it'd be great to use SPDX identifiers for the licenses. We now have all the open hardware licenses on the SPDX License List!  see https://spdx.org/licenses/ and  https://spdx.dev/ids/

please let me know how I can help!

**Comment by mwweinberg** [comment]
I'm also in to help figure this out

**Comment by mwweinberg** [comment]
(we were talking about this on a call this afternoon - it is just a totally random drive by issue-raising)

**Comment by jywarren** [comment]
Yay! Solved in https://github.com/jywarren/certification-mark-generator/pull/3, thank you so much!

Sorry for slow reply here, but SO GLAD we got this checked off. Thanks a ton!
